# The length of the trajectory in time domain, in seconds
trajectory_time_length: 6.0

# The spacing between two consecutive trajectory points, in seconds
trajectory_point_spacing: 0.1



# new
# ğ‘‡ğ‘ğ‘šğ‘–ğ‘› = ğ‘‡â„ğ‘’ ğ‘šğ‘–ğ‘›ğ‘–ğ‘šğ‘¢ğ‘š ğ‘¡ğ‘–ğ‘šğ‘’ ğ‘ğ‘™ğ‘™ğ‘œğ‘¤ğ‘’ğ‘‘ ğ‘“ğ‘œğ‘Ÿ ğ‘ ğ‘¡ğ‘Ÿğ‘ğ‘—ğ‘’ğ‘ğ‘¡ğ‘œğ‘Ÿğ‘¦ ğ‘¡ğ‘œ ğ‘ğ‘ğ‘ğ‘œğ‘¢ğ‘›ğ‘¡ ğ‘“ğ‘œğ‘Ÿ ğ‘Ÿğ‘’ğ‘ ğ‘ğ‘œğ‘›ğ‘ ğ‘’ ğ‘™ğ‘ğ‘”

tpmin: 0.0
maximum_deceleration_value: 0.0
min_downtrack: 1.0
x_gap: 10.0