# Copyright (C) 2019-2022 LEIDOS.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

# Int: Timer callback rate
# Units: millisecond
timer_cb_rate: 100

# Trajectory visualizer marker's arrow shaft diameter
x: 0.5

# Trajectory visualizer marker's arrow head diameter
y: 0.5

# If it is not zero, it specifies the trajectory arrow's head length.
z: 1.0

# Collision message display duration before disapearing(seconds)
t: 3.0