# Double: The minimum duration of a trajectory length
# Units: seconds
minimal_trajectory_duration : 6.0

# Double: The maximum acceptable jerk for completing maneuver 
# Units: meters per second cube
max_jerk_limit: 3.0

# Double: The rate at which the Guidance Node will process message
# Units: Hz
spin_rate_hz: 10

# Double: The minimum timestep used for planning trajectory
#Units: seconds
min_timestep : 0.1

# Double: The minimum acceptable instantaneous acceleration, after which constant speed is assumed, in m/s2
#Units: meters per second square
min_acceptable_acc: 0.001