# Double: The minimum duration of a trajectory length
# Units: seconds
minimal_trajectory_duration : 6.0

# Double: The rate at which the Guidance Node will process message
# Units: Hz
spin_rate_hz: 10

# Double: Size of timesteps between stopped trajectory points when stopped
# Units: seconds
stop_timestep : 0.1

# Double: Downtrack distance between trajectory points
# Units: m
trajectory_step_size : 1.0

# Double: Downtrack distance between trajectory points
# Units: percentage
accel_limit_multiplier : 0.7

# Double: Minimum speed the vehicle can command before being ready to stop
# Units: m/s
crawl_speed : 1.34112
