# spin rate, in hz
spin_rate: 10.0

# fitness score thredhold to determine if one ndt result is reliable or not
score_upper_limit: 60.0

# num of message thredhold to determin if ndt node is reliable or not
unreliable_message_upper_limit: 3

# localization mode for the platform
# 0 - ndt only
# 1 - GNSS only
# 2 - auto select between ndt and GNSS
localization_mode: 2
