timeHeadway: 3.5
standStillHeadway: 22.0
maxAccel: 1.5
Kp: 0.4
Kd: 0.0 #0.1
Ki: 0.03 #0.035
maxValue: 2.0
minValue: -10.0
cmdTmestamp: 100
adjustmentCap: 15.0
dt: 0.1
integratorMax: 30
integratorMin: -30
wheelBase: 3.39
lowpassGain: 0.5 #1.0
lookaheadRatio: 2.0 #1.7
minLookaheadDist: 15.0
correctionAngle: 0.0
integratorMax_pp: 0.1
integratorMin_pp: -0.1
Ki_pp: 0.012