/**:
  ros__parameters:
    # Long: Timeout for each service to be detected as available in milliseconds
    # Units: milliseconds
    service_timeout_ms : 2000

    # Long: Timeout for each service call in milliseconds
    # Units: milliseconds
    call_timeout_ms : 15000

    # String: The namespace for nodes in this subsystem. All nodes under this namespace will have their lifecycle's managed by this controller
    subsystem_namespace: /environment

    # Required subsystem controller nodes for the overall system to be functional and will have their lifecycle's managed
    # Since CARMA assumes connected vehicles in most cases the current minimum node set is from motion prediction up
    required_subsystem_nodes:
      - /environment/external_object

    # List of nodes which will not be directly managed by this subsystem controller 
    # but which are required to be operational for the subsystem to function
    unmanaged_required_nodes: 
      - /hardware_interface/velodyne_lidar_driver_wrapper_node

    # Boolean: If this flag is true then all nodes under subsystem_namespace are treated as required in addition to any nodes in required_subsystem_nodes
    full_subsystem_required: true