# Acceptable deviation in curvature along a section to be considered constant
# Units: 1/meters
curvature_epsilon: 3.0

# Number of consecutive points more than epsilon apart needed to consider a region
# to be linearly increasing
# Units: N/a
linearity_constraint: 2

# Limit of lateral acceleration around curves
# Units: m/s/s
lateral_accel_limit: 1.5

# Limit of longitudinal acceleartion while speeding up
# Units: m/s/s
longitudinal_accel_limit: 3.0

# Limit of longitudinal acceleartion while slowing down
# Units: m/s/s
longitudinal_decel_limit: 3.0

# Maximum speed along the route
# Units: m/s
max_speed: 10.0

# Ratio to downsample output waypoints (keep 1/n waypoints)
# Units: N/a
downsample_ratio: 2

# Coefficient on the single-pole lowpass filter for yaw
# Units: N/a
yaw_filter_coefficient: 1
