#  Copyright (C) 2018-2022 LEIDOS.
# 
#  Licensed under the Apache License, Version 2.0 (the "License"); you may not
#  use this file except in compliance with the License. You may obtain a copy of
#  the License at
# 
#  http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations under
#  the License.

# Configuration file for GitHub Actions 
# CI will report failure if any executed command returns and error status
# Operations performed are as follows
# Build source code Documentation
# Run Doxygen Action
# Deploy documentation static webpage to gh-pages

name: Doxygen Action

# Controls when the action will run. Triggers the workflow on push or pull Request events but only for the develop branch
on:
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Install graphvix to support Graph visualization and representing structural information as diagrams of abstract graphs and networks
    - name: Install graphviz
      run: sudo apt install graphviz && sudo dot -c
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Doxygen action for documentation of carma-platform source code by using mattnotmitt github actions workflow
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.9.4
      with:
        # Path to Doxyfile
        doxyfile-path: "./Doxyfile" # default is ./Doxyfile
        # Working directory
        working-directory: "." # default is .
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        external_repository: usdot-fhwa-stol/documentation
        publish_branch: gh-pages
        # default: gh-pages
        publish_dir: ./docs/html/
        destination_dir: ${{ github.event.repository.name }}
